import type { Lang, PlaceCategory } from '@/shared/types';

export const localeCookieName = 'dal_bbam_locale';
export const localeCookieMaxAge = 60 * 60 * 24 * 365;

const ko = {
  nav: { home: '홈', course: '코스', map: '지도', schedule: '일정', my: '마이' },
  common: {
    searchPlaceholder: '어디로 떠나볼까요?',
    all: '전체',
    viewAll: '전체보기',
    close: '닫기',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    share: '공유',
    retry: '다시 시도',
    loading: '불러오는 중…',
    signInRequired: '로그인이 필요합니다.',
    empty: '아직 표시할 항목이 없습니다.'
  },
  categories: {
    heritage: '문화유산',
    attraction: '관광지',
    food: '맛집',
    lodging: '숙박',
    festival: '축제',
    nature: '자연',
    experience: '체험'
  },
  home: {
    eyebrow: '경주, 신라와 달밤',
    headline: '특별한 하루를 시작해볼까요?',
    today: '오늘의 추천',
    themes: '테마 코스 추천',
    shorts: '쇼츠',
    community: '커뮤니티',
    stamps: '스탬프 투어'
  },
  map: {
    title: '경주 지도',
    currentLocation: '현재 위치',
    consentTitle: '위치정보 사용 동의',
    consentBody: '현재 위치와 스탬프 검증에만 사용하며 원시 위치 이력은 저장하지 않습니다.',
    allow: '동의하고 위치 사용',
    decline: '수동 탐색',
    nearbyLoading: '현재 위치 주변 관광지를 찾는 중…',
    nearbyCount: '반경 3km 내 관광지 {count}곳을 찾았습니다.',
    directions: '길찾기',
    walkingEstimate: '도보 예상',
    carRoute: '자동차 경로'
  },
  ai: {
    narration: 'AI 해설',
    listen: '음성 듣기',
    pause: '일시정지',
    disclosure: 'AI가 생성한 음성입니다.',
    fallback: '원문을 바탕으로 한 기본 해설입니다.',
    recommend: 'AI 코스 추천받기'
  },
  community: {
    title: '여행자 커뮤니티',
    newPost: '글쓰기',
    storyDraft: '사진으로 AI 스토리 초안',
    moderationRejected: '안전 또는 개인정보 검사를 통과하지 못했습니다.',
    explicitPublish: '초안을 확인하고 게시 버튼을 눌러야 공개됩니다.'
  }
} as const;

type MessagesShape = {
  nav: Record<keyof typeof ko.nav, string>;
  common: Record<keyof typeof ko.common, string>;
  categories: Record<PlaceCategory, string>;
  home: Record<keyof typeof ko.home, string>;
  map: Record<keyof typeof ko.map, string>;
  ai: Record<keyof typeof ko.ai, string>;
  community: Record<keyof typeof ko.community, string>;
};

export const messages: Record<Lang, MessagesShape> = {
  ko,
  en: {
    nav: { home: 'Home', course: 'Courses', map: 'Map', schedule: 'Schedule', my: 'My' },
    common: {
      searchPlaceholder: 'Where would you like to go?',
      all: 'All',
      viewAll: 'View all',
      close: 'Close',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      share: 'Share',
      retry: 'Try again',
      loading: 'Loading…',
      signInRequired: 'Please sign in.',
      empty: 'Nothing to show yet.'
    },
    categories: {
      heritage: 'Heritage',
      attraction: 'Attractions',
      food: 'Food',
      lodging: 'Stay',
      festival: 'Festivals',
      nature: 'Nature',
      experience: 'Experiences'
    },
    home: {
      eyebrow: 'Gyeongju under the Silla moon',
      headline: 'Ready to start a special day?',
      today: "Today's picks",
      themes: 'Themed routes',
      shorts: 'Shorts',
      community: 'Community',
      stamps: 'Stamp tour'
    },
    map: {
      title: 'Gyeongju map',
      currentLocation: 'My location',
      consentTitle: 'Allow location access',
      consentBody: 'Used only for your current location and stamp verification. Raw location history is not stored.',
      allow: 'Allow location',
      decline: 'Browse manually',
      nearbyLoading: 'Finding places near your current location…',
      nearbyCount: 'Found {count} places within 3 km.',
      directions: 'Directions',
      walkingEstimate: 'Walking estimate',
      carRoute: 'Driving route'
    },
    ai: {
      narration: 'AI narration',
      listen: 'Listen',
      pause: 'Pause',
      disclosure: 'This voice was generated by AI.',
      fallback: 'This is a source-based fallback narration.',
      recommend: 'Recommend an AI route'
    },
    community: {
      title: 'Traveler community',
      newPost: 'New post',
      storyDraft: 'AI story draft from photo',
      moderationRejected: 'This did not pass safety or privacy checks.',
      explicitPublish: 'Review the draft and press Publish before it becomes public.'
    }
  },
  ja: {
    nav: { home: 'ホーム', course: 'コース', map: '地図', schedule: '日程', my: 'マイ' },
    common: {
      searchPlaceholder: 'どこへ行きますか？',
      all: 'すべて',
      viewAll: 'すべて見る',
      close: '閉じる',
      save: '保存',
      delete: '削除',
      edit: '編集',
      share: '共有',
      retry: 'もう一度',
      loading: '読み込み中…',
      signInRequired: 'ログインが必要です。',
      empty: '表示する項目がありません。'
    },
    categories: {
      heritage: '文化遺産',
      attraction: '観光地',
      food: 'グルメ',
      lodging: '宿泊',
      festival: '祭り',
      nature: '自然',
      experience: '体験'
    },
    home: {
      eyebrow: '慶州、新羅と月夜',
      headline: '特別な一日を始めませんか？',
      today: '今日のおすすめ',
      themes: 'テーマコース',
      shorts: 'ショート',
      community: 'コミュニティ',
      stamps: 'スタンプツアー'
    },
    map: {
      title: '慶州地図',
      currentLocation: '現在地',
      consentTitle: '位置情報の利用同意',
      consentBody: '現在地とスタンプ確認だけに使用し、生の位置履歴は保存しません。',
      allow: '位置情報を許可',
      decline: '手動で探す',
      nearbyLoading: '現在地周辺の観光地を検索しています…',
      nearbyCount: '3km以内に{count}件の観光地が見つかりました。',
      directions: '経路案内',
      walkingEstimate: '徒歩予想',
      carRoute: '自動車経路'
    },
    ai: {
      narration: 'AI解説',
      listen: '音声を聞く',
      pause: '一時停止',
      disclosure: 'AIが生成した音声です。',
      fallback: '原文を基にした基本解説です。',
      recommend: 'AIコースを提案'
    },
    community: {
      title: '旅行者コミュニティ',
      newPost: '投稿する',
      storyDraft: '写真からAIストーリー下書き',
      moderationRejected: '安全性または個人情報の検査を通過しませんでした。',
      explicitPublish: '下書きを確認し、投稿ボタンを押すまで公開されません。'
    }
  },
  zh: {
    nav: { home: '首页', course: '路线', map: '地图', schedule: '行程', my: '我的' },
    common: {
      searchPlaceholder: '想去哪里？',
      all: '全部',
      viewAll: '查看全部',
      close: '关闭',
      save: '保存',
      delete: '删除',
      edit: '编辑',
      share: '分享',
      retry: '重试',
      loading: '加载中…',
      signInRequired: '请先登录。',
      empty: '暂无内容。'
    },
    categories: {
      heritage: '文化遗产',
      attraction: '景点',
      food: '美食',
      lodging: '住宿',
      festival: '庆典',
      nature: '自然',
      experience: '体验'
    },
    home: {
      eyebrow: '庆州，新罗与月夜',
      headline: '开启特别的一天吧？',
      today: '今日推荐',
      themes: '主题路线',
      shorts: '短视频',
      community: '社区',
      stamps: '印章之旅'
    },
    map: {
      title: '庆州地图',
      currentLocation: '当前位置',
      consentTitle: '位置使用同意',
      consentBody: '仅用于当前位置和印章验证，不保存原始位置历史。',
      allow: '同意使用位置',
      decline: '手动浏览',
      nearbyLoading: '正在查找当前位置附近的景点…',
      nearbyCount: '在3公里范围内找到{count}个景点。',
      directions: '路线',
      walkingEstimate: '步行预计',
      carRoute: '驾车路线'
    },
    ai: {
      narration: 'AI讲解',
      listen: '播放语音',
      pause: '暂停',
      disclosure: '该语音由AI生成。',
      fallback: '这是基于原文的基础讲解。',
      recommend: 'AI路线推荐'
    },
    community: {
      title: '旅行者社区',
      newPost: '发布',
      storyDraft: '根据照片生成AI故事草稿',
      moderationRejected: '未通过安全或个人信息检查。',
      explicitPublish: '确认草稿并点击发布后才会公开。'
    }
  }
};

export function isLang(value: string | null | undefined): value is Lang {
  return value !== null && value !== undefined && value in messages;
}

export function categoryLabel(category: PlaceCategory, lang: Lang): string {
  return messages[lang].categories[category];
}
