import type { Lang } from '@/shared/types';

const ko = {
  community: {
    all: '전체', review: '후기', tip: '꿀팁', food: '맛집', lodging: '숙소',
    loadFailed: '커뮤니티를 불러오지 못했습니다.', bookmarkFailed: '북마크를 변경하지 못했습니다.',
    deleteConfirm: '이 게시물을 삭제할까요?', deleteFailed: '게시물을 삭제하지 못했습니다.', deleted: '게시물을 삭제했습니다.', saved: '게시물을 저장했습니다.',
    subtitle: '경주 여행의 순간과 꿀팁을 나눠보세요', searchLabel: '커뮤니티 검색', searchPlaceholder: '후기, 장소, 여행 팁 검색', filtersLabel: '커뮤니티 필터', savedFilter: '저장',
    loadErrorTitle: '커뮤니티를 불러오지 못했어요', emptyTitle: '아직 표시할 여행 이야기가 없어요', emptySearch: '다른 검색어나 필터를 선택해 주세요.', emptyDefault: '첫 번째 경주 여행 이야기를 남겨 보세요.', resetFilters: '필터 초기화',
    placeLinked: '관광지 연결', attachmentPhoto: '{title} 첨부 사진', bookmarkRemove: '북마크 해제', bookmarkSave: '북마크 저장', edit: '수정', delete: '삭제', loading: '불러오는 중', loadingList: '커뮤니티를 불러오는 중',
    discardConfirm: '작성 중인 내용을 버리고 닫을까요?', uploadPrepareFailed: '업로드를 준비하지 못했습니다.', browserConfigRequired: 'Supabase 브라우저 설정이 필요합니다.', imageRejected: '이미지 검사를 통과하지 못했습니다.', imageApproved: '이미지 안전 검사를 통과했습니다.', imageUploadFailed: '이미지를 업로드하지 못했습니다.', storyFailed: '스토리 초안을 만들지 못했습니다.', moderationMissing: '현재 안전 검사 서비스가 설정되지 않아 게시물을 저장할 수 없습니다. 관리자에게 OpenAI 설정을 요청해 주세요.', saveFailed: '게시물을 저장하지 못했습니다.',
    cancel: '취소', save: '저장', close: '닫기', editPost: '게시글 수정', newPost: '새 게시글', prompt: '어떤 이야기를 나눌까요?', categoryLabel: '게시글 카테고리', linkedPlace: '연결된 관광지 · {id}', photo: '사진', fileHint: 'JPEG·PNG·WebP, 10MB 이하', previewAlt: '게시글 사진 미리보기', aiDraft: 'AI 초안', addPhoto: '여행 사진을 추가해 주세요', title: '제목', titlePlaceholder: '제목을 입력해 주세요', content: '내용', contentPlaceholder: '경주 여행 이야기를 들려주세요', rating: '별점', points: '{value}점', privacyNote: '사진과 글은 안전·개인정보 검사 후 공개됩니다. AI 초안은 자동으로 게시되지 않습니다.', moderationUnavailable: '현재 안전 검사 서비스가 설정되지 않아 작성·수정을 완료할 수 없습니다. 배포 또는 데모 환경에 OpenAI 설정이 필요합니다.', saveChanges: '수정 내용 저장', publish: '게시하기',
    postLoadFailed: '게시물을 불러오지 못했습니다.', commentsLoadFailed: '댓글을 불러오지 못했습니다.', commentSaveFailed: '댓글을 저장하지 못했습니다.', commentDeleteFailed: '댓글을 삭제하지 못했습니다.', reportConfirm: '이 게시물을 운영자에게 신고할까요?', reportSuccess: '신고를 접수했습니다.', reportFailed: '신고를 접수하지 못했습니다.', blockConfirm: '이 작성자를 차단하고 게시물을 숨길까요?', blockFailed: '작성자를 차단하지 못했습니다.', postNotFound: '게시물을 찾을 수 없습니다.', backToList: '목록으로', backToListLabel: '커뮤니티 목록으로', postMenu: '게시글 메뉴', report: '신고', blockAuthor: '작성자 차단', photoAlt: '{title} 사진 {index}', edited: '수정됨', comments: '댓글', commentInput: '댓글 입력', commentPlaceholder: '여행 이야기에 따뜻한 댓글을 남겨보세요', commentPublish: '댓글 게시', commentDelete: '댓글 삭제', firstComment: '첫 댓글을 남겨보세요.', changesSaved: '수정 내용을 저장했습니다.', detailLoading: '게시물을 불러오는 중', removePhoto: '사진 삭제', localModerationNote: 'AI 안전 검사가 꺼져 있어 개인정보·금칙어 기본 검사만 적용됩니다. 사진은 형식·용량만 확인합니다.'
  },
  course: {
    walking: '도보', car: '자동차', public: '대중교통', loadRecommendFailed: '코스를 추천할 수 없습니다.', saveFailed: '코스를 저장할 수 없습니다.', copied: '공유 링크를 복사했습니다.', header: 'AI 추천 코스', eyebrow: '실제 관광지 데이터로', headline: '내 여행 조건에 맞는 코스를 만들어요', purpose: '여행 목적', purposePlaceholder: '예: 부모님과 신라 역사 여행', duration: '기간', days: '{day}일', companion: '동행', solo: '혼자', couple: '연인', family: '가족', friends: '친구', group: '단체', pace: '여행 속도', relaxed: '여유롭게', balanced: '균형 있게', packed: '알차게', transport: '교통수단', interests: '관심사', aiPlan: 'AI 플랜', fallbackPlan: '기본 플랜', shareLabel: '코스 공유', saveLabel: '코스 저장', durationSummary: '{distance}km · 약 {hours}시간', recommendedPlace: '추천 장소', minutes: '{minutes}분', curatedTitle: '큐레이션 추천 코스', curatedDescription: '테마별로 미리 준비된 검증된 코스예요.', courseSuffix: '코스', deletedPlace: '삭제된 장소', savedNotice: '코스를 저장했습니다. 아래 내 코스에서 다시 볼 수 있어요.', shareFailed: '공유하지 못했습니다.', myCoursesTitle: '내 코스', myCoursesDescription: '저장한 AI 추천 코스와 공유 링크입니다.'
  },
  itinerary: {
    loadFailed: '일정을 불러오지 못했습니다.', createFailed: '일정을 만들 수 없습니다.', saveOrderFailed: '일정 순서를 저장하지 못했습니다.', saveFailed: '일정을 저장하지 못했습니다.', invalidMetadata: '올바른 제목과 시작일·종료일을 입력해 주세요.', updateFailed: '일정을 수정하지 못했습니다.', deleteConfirm: '“{title}” 일정을 삭제할까요?', deleteFailed: '일정을 삭제하지 못했습니다.', defaultTitle: '나의 경주 여행', header: '내 일정', subtitle: '{start} ~ {end} · 장소 {count}곳', shareLabel: '일정 공유', emptyTitle: '아직 일정이 없어요', emptyDescription: '새 일정을 만들고 장바구니의 장소를 추가해 보세요.', create: '일정 만들기', newSchedule: '새 일정', close: '닫기', edit: '일정 수정', delete: '삭제', title: '일정 제목', startDate: '시작일', endDate: '종료일', saving: '저장 중…', saveChanges: '변경 저장', timeline: '타임라인', calendar: '캘린더', timeUndecided: '시간 미정', noPlaces: '아직 추가한 장소가 없습니다.', minutes: '{minutes}분', visitDate: '{name} 방문일', visitTime: '{name} 방문 시간', moveUp: '{name} 위로 이동', moveDown: '{name} 아래로 이동', drag: '{name} 드래그하여 순서 변경', add: '추가', copied: '공유 링크를 복사했습니다.', shareFailed: '공유하지 못했습니다.'
  },
  cart: {
    loadFailed: '장바구니를 불러오지 못했습니다.', saveFailed: '장소를 저장하지 못했습니다.', saved: '장소를 장바구니에 저장했습니다.', deleteFailed: '장소를 삭제하지 못했습니다.', scheduleLoadFailed: '일정을 불러오지 못했습니다.', defaultScheduleTitle: '장바구니 여행', scheduleCreateFailed: '일정을 만들지 못했습니다.', schedulePrepareFailed: '일정을 준비하지 못했습니다.', scheduleAddFailed: '일정에 추가하지 못했습니다.', addedToSchedule: '{count}곳을 일정에 추가했습니다.', header: '여행 장바구니', save: '저장', emptyTitle: '저장한 장소가 없어요', emptyDescription: '위 목록에서 장소를 골라 장바구니에 저장해 보세요.', delete: '삭제', selected: '선택', count: '{count}곳', traveler: '여행자', addToSchedule: '일정에 추가'
  },
  place: {
    loadFailed: '관광지를 불러오지 못했습니다.', narrationFailed: 'AI 해설을 불러오지 못했습니다.', audioFailed: '음성을 재생하지 못했습니다.', cartSaved: '장바구니에 저장했습니다.', saveFailed: '저장하지 못했습니다.', notFound: '관광지를 찾을 수 없어요', backToMap: '지도 돌아가기', information: '관광 정보', hours: '운영시간', phone: '연락처', narrationPrompt: '장소 이야기를 1분으로 들어보세요', saveToCart: '장바구니에 저장', copied: '링크를 복사했습니다.', shareFailed: '공유하지 못했습니다.'
  },
  auth: {
    kakaoNotConfigured: '카카오 로그인 서버 설정을 확인해 주세요.', kakaoCancelled: '카카오 로그인이 취소되었습니다.', kakaoAuthorizationFailed: '카카오 인증 요청을 완료하지 못했습니다.', kakaoCodeMissing: '카카오 인가 코드가 전달되지 않았습니다. 다시 시도해 주세요.', kakaoStateMismatch: '로그인 요청이 만료되었거나 올바르지 않습니다. 다시 시도해 주세요.', kakaoTokenFailed: '카카오 인증 토큰을 발급받지 못했습니다. 다시 시도해 주세요.', kakaoUserFailed: '카카오 사용자 정보를 불러오지 못했습니다.', kakaoPersistenceFailed: '서비스 회원 정보를 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.', kakaoStateExpired: '로그인 요청이 만료되었습니다. 다시 시도해 주세요.', kakaoLoginFailed: '카카오 로그인 중 오류가 발생했습니다.', googleNotConfigured: 'Google 로그인 서버 설정을 확인해 주세요.', googleAuthorizationFailed: 'Google 로그인을 시작하지 못했습니다.', callbackFailed: '로그인 링크가 만료되었거나 올바르지 않습니다.', demoFailed: '데모 로그인에 실패했습니다.', networkError: '네트워크 연결을 확인해 주세요.', enterResetEmail: '위 이메일 칸에 가입한 이메일을 먼저 입력해 주세요.', resetMailFailed: '재설정 메일을 보내지 못했습니다.', resetMailSent: '계정이 존재하면 비밀번호 재설정 메일이 발송됩니다.', nameTooShort: '이름은 2자 이상 입력해 주세요.', passwordMismatch: '비밀번호가 일치하지 않습니다.', genericError: '오류가 발생했습니다.', verificationSent: '인증 메일을 보냈습니다. 메일의 링크를 눌러 인증하면 회원가입이 완료됩니다.', header: '로그인/회원가입', login: '로그인', signup: '회원가입', email: '이메일 주소', name: '이름 (2자 이상)', password: '비밀번호', passwordConfirm: '비밀번호 확인', hidePassword: '비밀번호 숨기기', showPassword: '비밀번호 보기', hidePasswordConfirm: '비밀번호 확인 숨기기', showPasswordConfirm: '비밀번호 확인 보기', join: '가입하기', forgotPassword: '비밀번호 찾기', kakaoLogin: '카카오 로그인', googleLogin: 'Google 로그인', demoLogin: '데모 계정으로 체험하기', continuePrefix: '계속하면', terms: '이용약관', privacy: '개인정보처리방침', continueSuffix: '에 동의한 것으로 봅니다.', minEight: '비밀번호는 8자 이상 입력해 주세요.', authUnavailable: '인증 서버가 설정되지 않았습니다.', updateFailed: '비밀번호를 변경하지 못했습니다. 링크가 만료되었는지 확인해 주세요.', updated: '비밀번호를 변경했습니다', returnService: '서비스로 돌아가기', setNewPassword: '새 비밀번호 설정', passwordHint: '다른 서비스에서 사용하지 않는 8자 이상의 비밀번호를 사용해 주세요.', newPassword: '새 비밀번호', change: '변경하기'
  },
  settings: {
    loadFailed: '계정 정보를 불러오지 못했습니다.', deleteFailed: '계정을 삭제하지 못했습니다.', networkError: '네트워크 연결을 확인해 주세요.', title: '내 계정', traveler: '여행자', loading: '불러오는 중', terms: '이용약관', privacy: '개인정보처리방침', locationTerms: '위치기반서비스 이용약관', deleteTitle: '계정 영구 삭제', deleteDescription: '일정, 스탬프, 게시물과 업로드 파일을 삭제하며 복구할 수 없습니다. 계속하려면 아래에 DELETE를 입력하세요.', deleteConfirmLabel: '계정 삭제 확인 문구', deleteAction: '계정과 데이터 삭제'
  },
  stamp: { fallbackDescription: '경주 현장 스탬프 대상 관광지입니다.', fallbackAddress: '경주시', fieldCheck: '현장 확인', hoursCheck: '운영 시간 확인', tag: '스탬프', loadFailed: '스탬프 도감을 불러오지 못했습니다.', targetsMissing: '스탬프 대상 데이터가 준비되지 않았습니다.', retryNetwork: '네트워크 연결을 확인한 뒤 다시 시도해 주세요.', checkpointFirst: '현장 안내판의 QR 체크포인트를 먼저 스캔해 주세요.', geoUnsupported: '이 브라우저는 위치정보를 지원하지 않습니다.', persistFailed: '스탬프가 저장되지 않았습니다. 다시 시도해 주세요.', duplicate: '이미 획득한 스탬프입니다.', verified: '현장 확인 완료 · 거리 {distance}m{delay}', rewardDelay: ' · 배지/리워드 반영 중', obtainFailed: '스탬프를 획득하지 못했습니다.', networkError: '네트워크 연결을 확인해 주세요.', permissionDenied: '위치 권한이 거부되었습니다. 브라우저 설정에서 위치 권한을 허용해 주세요.', locationFailed: '현재 위치를 확인하지 못했습니다.', consentSaveFailed: '위치정보 동의를 저장하지 못했습니다.', consentDetail: '{name} 현장 반경 안에 있는지 한 번 확인하며, 원시 위치 이력은 저장하지 않습니다.', backAll: '전체보기', eyebrow: 'GPS와 현장 체크포인트로 확인하는', title: '경주 AI 스탬프 투어', checkpointScanned: '현장 QR 체크포인트를 확인했어요', checkpointLinked: '연결된 장소의 현장 확인 버튼을 눌러 주세요.', checkpointThis: '해당 장소의 현장 확인 버튼을 눌러 주세요.', loadErrorTitle: '스탬프 도감을 연결하지 못했어요', retry: '다시 불러오기', progressPrompt: '승인된 관광지 스탬프를 모아보세요', collected: '모은 스탬프', badges: '획득 배지', rewards: '디지털 리워드', badgeWarning: '배지 정보 반영이 지연되고 있습니다. 스탬프 획득 기록에는 영향이 없습니다.', catalogueTitle: '경주 스탬프 도감', catalogueDescription: '승인된 AI 아트가 우선 표시되며, 없으면 관광지 사진을 사용합니다.', loading: '불러오는 중', emptyTitle: '운영 중인 스탬프 대상이 없습니다', emptyDescription: '장소 동기화와 stamp target 설정을 확인해 주세요.', stampAlt: '{name} 스탬프', artDisplayFailed: 'AI 아트 표시 실패', photoFallback: ' · 사진 대체', modelTitle: '생성 모델: {model}', approvedArt: '승인 AI 아트', artGenerationFailed: 'AI 아트 생성 실패', artGenerating: 'AI 아트 생성 중', artPending: 'AI 아트 승인 대기', attractionPhotoFailed: '관광지 사진 표시 실패', photoNoAi: '관광지 사진 · AI 미생성', imagePreparing: '이미지 준비 중', qrReady: '현장 QR 확인됨', qrRequired: '현장 QR 필요', recheck: '다시 확인', check: '현장 확인', explore: '다른 여행 코스 보기', gpsWaiting: 'GPS 신호를 기다리는 중… (최대 15초)', gpsSearching: 'GPS 확인 중 · 정확도 {accuracy}m (기준 {max}m 이내)', gpsTimeout: '충분히 정확한 GPS 신호를 받지 못했습니다. 하늘이 트인 곳에서 다시 시도해 주세요.', distanceHint: '내 위치에서 {distance}m · 허용 반경 {radius}m', lastFix: '마지막 GPS 정확도 {accuracy}m' },
  shorts: { loadMore: '쇼츠 더 보기', loadFailed: '쇼츠를 불러오지 못했습니다.', audioFailed: '음성 해설을 재생하지 못했습니다.', reactionFailed: '반응을 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.', shareFailed: '공유 링크를 만들지 못했습니다.', title: '경주 쇼츠', introduction: '문화재가 들려주는 이야기, 짧은 영상으로 만나요.', placeDetails: '장소 정보 보기', filters: '쇼츠 태그 필터', loading: '쇼츠 불러오는 중', likeCount: '좋아요 {count}개', reactionsUnavailable: '샘플 쇼츠에서는 좋아요·저장이 지원되지 않습니다.' },
  video: { videoLabel: '{title} 영상', youtubeTitle: '{title} YouTube 영상', buffering: '영상을 불러오는 중', failed: '영상을 재생할 수 없어 대표 이미지를 표시하고 있습니다.', pause: '영상 일시정지', play: '영상 재생', unmute: '영상 소리 켜기', mute: '영상 음소거' },
  share: { loadFailed: '공유 내용을 불러오지 못했습니다.', cannotOpen: '공유 링크를 열 수 없어요', sharedCourse: '공유된 코스', sharedSchedule: '공유된 일정', minutes: '{minutes}분', removedPlace: '삭제된 장소' },
  offline: { title: '인터넷 연결이 필요해요', description: '연결이 복구되면 여행 정보와 내 일정을 다시 불러올 수 있습니다.', retry: '다시 연결하기' }
} as const;

type UiMessagesShape = {
  [Section in keyof typeof ko]: Record<keyof (typeof ko)[Section], string>;
};

export const uiMessages: Record<Lang, UiMessagesShape> = {
  ko,
  en: {
    community: {
      all: 'All', review: 'Reviews', tip: 'Tips', food: 'Food', lodging: 'Stay',
      loadFailed: 'Could not load the community.', bookmarkFailed: 'Could not update the bookmark.', deleteConfirm: 'Delete this post?', deleteFailed: 'Could not delete the post.', deleted: 'Post deleted.', saved: 'Post saved.', subtitle: 'Share your Gyeongju moments and travel tips', searchLabel: 'Search community', searchPlaceholder: 'Search reviews, places, and travel tips', filtersLabel: 'Community filters', savedFilter: 'Saved', loadErrorTitle: 'Could not load the community', emptyTitle: 'No travel stories to show yet', emptySearch: 'Try another search term or filter.', emptyDefault: 'Share the first Gyeongju travel story.', resetFilters: 'Reset filters', placeLinked: 'Linked place', attachmentPhoto: '{title} attachment', bookmarkRemove: 'Remove bookmark', bookmarkSave: 'Save bookmark', edit: 'Edit', delete: 'Delete', loading: 'Loading', loadingList: 'Loading community',
      discardConfirm: 'Discard your changes and close?', uploadPrepareFailed: 'Could not prepare the upload.', browserConfigRequired: 'Supabase browser configuration is required.', imageRejected: 'The image did not pass review.', imageApproved: 'The image passed the safety review.', imageUploadFailed: 'Could not upload the image.', storyFailed: 'Could not create a story draft.', moderationMissing: 'Posts cannot be saved because the safety review service is unavailable. Ask an administrator to configure OpenAI.', saveFailed: 'Could not save the post.', cancel: 'Cancel', save: 'Save', close: 'Close', editPost: 'Edit post', newPost: 'New post', prompt: 'What would you like to share?', categoryLabel: 'Post category', linkedPlace: 'Linked place · {id}', photo: 'Photo', fileHint: 'JPEG, PNG, or WebP · up to 10 MB', previewAlt: 'Post photo preview', aiDraft: 'AI draft', addPhoto: 'Add a travel photo', title: 'Title', titlePlaceholder: 'Enter a title', content: 'Story', contentPlaceholder: 'Share your Gyeongju travel story', rating: 'Rating', points: '{value} stars', privacyNote: 'Photos and text are published after safety and privacy checks. AI drafts are never published automatically.', moderationUnavailable: 'Writing and editing are unavailable because the safety review service is not configured. OpenAI must be configured for this environment.', saveChanges: 'Save changes', publish: 'Publish',
      postLoadFailed: 'Could not load the post.', commentsLoadFailed: 'Could not load comments.', commentSaveFailed: 'Could not save the comment.', commentDeleteFailed: 'Could not delete the comment.', reportConfirm: 'Report this post to the moderators?', reportSuccess: 'Report submitted.', reportFailed: 'Could not submit the report.', blockConfirm: 'Block this author and hide the post?', blockFailed: 'Could not block the author.', postNotFound: 'Post not found.', backToList: 'Back to list', backToListLabel: 'Back to community', postMenu: 'Post menu', report: 'Report', blockAuthor: 'Block author', photoAlt: '{title} photo {index}', edited: 'Edited', comments: 'Comments', commentInput: 'Comment', commentPlaceholder: 'Leave a thoughtful comment', commentPublish: 'Post comment', commentDelete: 'Delete comment', firstComment: 'Be the first to comment.', changesSaved: 'Changes saved.', detailLoading: 'Loading post', removePhoto: 'Remove photo', localModerationNote: 'AI safety review is off, so only the basic personal-data and keyword checks apply. Photos are checked for type and size only.'
    },
    course: {
      walking: 'Walking', car: 'Car', public: 'Public transit', loadRecommendFailed: 'Could not recommend a route.', saveFailed: 'Could not save the route.', copied: 'Share link copied.', header: 'AI route planner', eyebrow: 'Built from real attraction data', headline: 'Create a route that fits your trip', purpose: 'Trip goal', purposePlaceholder: 'e.g. Silla history with my parents', duration: 'Duration', days: '{day} days', companion: 'Traveling with', solo: 'Solo', couple: 'Partner', family: 'Family', friends: 'Friends', group: 'Group', pace: 'Pace', relaxed: 'Relaxed', balanced: 'Balanced', packed: 'Packed', transport: 'Transportation', interests: 'Interests', aiPlan: 'AI plan', fallbackPlan: 'Basic plan', shareLabel: 'Share route', saveLabel: 'Save route', durationSummary: '{distance} km · about {hours} hr', recommendedPlace: 'Recommended place', minutes: '{minutes} min', curatedTitle: 'Curated routes', curatedDescription: 'Verified routes prepared for each theme.', courseSuffix: 'route', deletedPlace: 'Place unavailable', savedNotice: 'Course saved. Find it under My courses below.', shareFailed: 'Could not share.', myCoursesTitle: 'My courses', myCoursesDescription: 'Saved AI courses and their share links.'
    },
    itinerary: {
      loadFailed: 'Could not load your schedules.', createFailed: 'Could not create a schedule.', saveOrderFailed: 'Could not save the schedule order.', saveFailed: 'Could not save the schedule.', invalidMetadata: 'Enter a valid title, start date, and end date.', updateFailed: 'Could not update the schedule.', deleteConfirm: 'Delete “{title}”?', deleteFailed: 'Could not delete the schedule.', defaultTitle: 'My Gyeongju trip', header: 'My schedule', subtitle: '{start} – {end} · {count} places', shareLabel: 'Share schedule', emptyTitle: 'No schedule yet', emptyDescription: 'Create a schedule and add places from your cart.', create: 'Create schedule', newSchedule: 'New schedule', close: 'Close', edit: 'Edit schedule', delete: 'Delete', title: 'Schedule title', startDate: 'Start date', endDate: 'End date', saving: 'Saving…', saveChanges: 'Save changes', timeline: 'Timeline', calendar: 'Calendar', timeUndecided: 'Time not set', noPlaces: 'No places added yet.', minutes: '{minutes} min', visitDate: '{name} visit date', visitTime: '{name} visit time', moveUp: 'Move {name} up', moveDown: 'Move {name} down', drag: 'Drag {name} to reorder', add: 'Add', copied: 'Share link copied.', shareFailed: 'Could not share.'
    },
    cart: {
      loadFailed: 'Could not load your cart.', saveFailed: 'Could not save the place.', saved: 'Place saved to your cart.', deleteFailed: 'Could not remove the place.', scheduleLoadFailed: 'Could not load your schedules.', defaultScheduleTitle: 'Cart trip', scheduleCreateFailed: 'Could not create a schedule.', schedulePrepareFailed: 'Could not prepare the schedule.', scheduleAddFailed: 'Could not add places to the schedule.', addedToSchedule: 'Added {count} places to the schedule.', header: 'Travel cart', save: 'Save', emptyTitle: 'No saved places', emptyDescription: 'Choose a place above and save it to your cart.', delete: 'Delete', selected: 'Selected', count: '{count}', traveler: 'Traveler', addToSchedule: 'Add to schedule'
    },
    place: {
      loadFailed: 'Could not load the place.', narrationFailed: 'Could not load the AI narration.', audioFailed: 'Could not play the audio.', cartSaved: 'Saved to your cart.', saveFailed: 'Could not save.', notFound: 'Place not found', backToMap: 'Back to map', information: 'Visitor information', hours: 'Hours', phone: 'Phone', narrationPrompt: 'Hear this place’s story in one minute', saveToCart: 'Save to cart', copied: 'Link copied.', shareFailed: 'Could not share.'
    },
    auth: {
      kakaoNotConfigured: 'Check the Kakao login server configuration.', kakaoCancelled: 'Kakao login was canceled.', kakaoAuthorizationFailed: 'Could not complete Kakao authorization.', kakaoCodeMissing: 'Kakao did not return an authorization code. Try again.', kakaoStateMismatch: 'This login request expired or is invalid. Try again.', kakaoTokenFailed: 'Could not issue a Kakao access token. Try again.', kakaoUserFailed: 'Could not load your Kakao profile.', kakaoPersistenceFailed: 'Could not save your account. Try again shortly.', kakaoStateExpired: 'This login request expired. Try again.', kakaoLoginFailed: 'An error occurred during Kakao login.', googleNotConfigured: 'Check the Google login server configuration.', googleAuthorizationFailed: 'Could not start Google login.', callbackFailed: 'This login link expired or is invalid.', demoFailed: 'Demo login failed.', networkError: 'Check your network connection.', enterResetEmail: 'Enter your account email above first.', resetMailFailed: 'Could not send the reset email.', resetMailSent: 'If the account exists, a password reset email has been sent.', nameTooShort: 'Enter at least 2 characters for your name.', passwordMismatch: 'Passwords do not match.', genericError: 'Something went wrong.', verificationSent: 'We sent a verification email. Follow its link to finish signing up.', header: 'Log in / Sign up', login: 'Log in', signup: 'Sign up', email: 'Email address', name: 'Name (2+ characters)', password: 'Password', passwordConfirm: 'Confirm password', hidePassword: 'Hide password', showPassword: 'Show password', hidePasswordConfirm: 'Hide password confirmation', showPasswordConfirm: 'Show password confirmation', join: 'Create account', forgotPassword: 'Forgot password?', kakaoLogin: 'Log in with Kakao', googleLogin: 'Log in with Google', demoLogin: 'Try the demo account', continuePrefix: 'By continuing, you agree to the', terms: 'Terms of Service', privacy: 'Privacy Policy', continueSuffix: '.', minEight: 'Enter a password of at least 8 characters.', authUnavailable: 'The authentication server is not configured.', updateFailed: 'Could not change the password. Check whether the link expired.', updated: 'Password changed', returnService: 'Return to the app', setNewPassword: 'Set a new password', passwordHint: 'Use a password of at least 8 characters that you do not use elsewhere.', newPassword: 'New password', change: 'Change password'
    },
    settings: {
      loadFailed: 'Could not load your account.', deleteFailed: 'Could not delete your account.', networkError: 'Check your network connection.', title: 'My account', traveler: 'Traveler', loading: 'Loading', terms: 'Terms of Service', privacy: 'Privacy Policy', locationTerms: 'Location Service Terms', deleteTitle: 'Permanently delete account', deleteDescription: 'This permanently removes schedules, stamps, posts, and uploaded files. Type DELETE below to continue.', deleteConfirmLabel: 'Account deletion confirmation', deleteAction: 'Delete account and data'
    },
    stamp: { fallbackDescription: 'A participating on-site stamp destination in Gyeongju.', fallbackAddress: 'Gyeongju', fieldCheck: 'On-site check', hoursCheck: 'Check opening hours', tag: 'Stamp', loadFailed: 'Could not load the stamp collection.', targetsMissing: 'Stamp destination data is not ready.', retryNetwork: 'Check your network connection and try again.', checkpointFirst: 'Scan the QR checkpoint on the on-site sign first.', geoUnsupported: 'This browser does not support location services.', persistFailed: 'The stamp was not saved. Try again.', duplicate: 'You already collected this stamp.', verified: 'On-site check complete · {distance} m away{delay}', rewardDelay: ' · Updating badges/rewards', obtainFailed: 'Could not collect the stamp.', networkError: 'Check your network connection.', permissionDenied: 'Location permission was denied. Allow it in your browser settings.', locationFailed: 'Could not determine your current location.', consentSaveFailed: 'Could not save your location consent.', consentDetail: 'We will check once whether you are within the on-site radius of {name}. Raw location history is not stored.', backAll: 'View all', eyebrow: 'Verified with GPS and an on-site checkpoint', title: 'Gyeongju AI Stamp Tour', checkpointScanned: 'On-site QR checkpoint confirmed', checkpointLinked: 'Tap the on-site check button for the linked place.', checkpointThis: 'Tap the on-site check button for this place.', loadErrorTitle: 'Could not connect the stamp collection', retry: 'Reload', progressPrompt: 'Collect stamps from approved destinations', collected: 'Stamps', badges: 'Badges', rewards: 'Digital rewards', badgeWarning: 'Badge updates are delayed. Your stamp records are unaffected.', catalogueTitle: 'Gyeongju Stamp Collection', catalogueDescription: 'Approved AI artwork appears first; destination photos are used when unavailable.', loading: 'Loading', emptyTitle: 'No active stamp destinations', emptyDescription: 'Check place synchronization and the stamp target configuration.', stampAlt: '{name} stamp', artDisplayFailed: 'AI artwork failed to display', photoFallback: ' · Using photo', modelTitle: 'Generation model: {model}', approvedArt: 'Approved AI artwork', artGenerationFailed: 'AI artwork generation failed', artGenerating: 'Generating AI artwork', artPending: 'AI artwork awaiting approval', attractionPhotoFailed: 'Destination photo failed to display', photoNoAi: 'Destination photo · No AI artwork', imagePreparing: 'Preparing image', qrReady: 'On-site QR confirmed', qrRequired: 'On-site QR required', recheck: 'Check again', check: 'On-site check', explore: 'Explore other routes', gpsWaiting: 'Waiting for a GPS fix… (up to 15 s)', gpsSearching: 'Checking GPS · accuracy {accuracy} m (needs ≤ {max} m)', gpsTimeout: 'Could not get an accurate enough GPS fix. Try again with a clear view of the sky.', distanceHint: '{distance} m from you · allowed radius {radius} m', lastFix: 'Last GPS accuracy {accuracy} m' },
    shorts: { loadMore: 'Load more stories', loadFailed: 'Could not load Shorts.', audioFailed: 'Could not play the narration.', reactionFailed: 'Could not save your reaction. Try again shortly.', shareFailed: 'Could not create a share link.', title: 'Gyeongju Shorts', introduction: 'Meet Gyeongju’s heritage through short video stories.', placeDetails: 'Explore this place', filters: 'Shorts tag filters', loading: 'Loading Shorts', likeCount: '{count} likes', reactionsUnavailable: 'Likes and saves are unavailable for sample Shorts.' },
    video: { videoLabel: '{title} video', youtubeTitle: '{title} YouTube video', buffering: 'Loading the video', failed: 'The video is unavailable, so the cover image is shown.', pause: 'Pause video', play: 'Play video', unmute: 'Turn video sound on', mute: 'Mute video' },
    share: { loadFailed: 'Could not load the shared plan.', cannotOpen: 'This share link cannot be opened', sharedCourse: 'Shared course', sharedSchedule: 'Shared schedule', minutes: '{minutes} min', removedPlace: 'Removed place' },
    offline: { title: 'You’re offline', description: 'Reconnect to reload travel information and your schedule.', retry: 'Try again' }
  },
  ja: {
    community: {
      all: 'すべて', review: 'レビュー', tip: '旅のコツ', food: 'グルメ', lodging: '宿泊', loadFailed: 'コミュニティを読み込めませんでした。', bookmarkFailed: 'ブックマークを更新できませんでした。', deleteConfirm: 'この投稿を削除しますか？', deleteFailed: '投稿を削除できませんでした。', deleted: '投稿を削除しました。', saved: '投稿を保存しました。', subtitle: '慶州旅行の思い出やコツを共有しましょう', searchLabel: 'コミュニティ検索', searchPlaceholder: 'レビュー・場所・旅行のコツを検索', filtersLabel: 'コミュニティフィルター', savedFilter: '保存済み', loadErrorTitle: 'コミュニティを読み込めません', emptyTitle: '表示する旅行ストーリーがありません', emptySearch: '別の検索語やフィルターをお試しください。', emptyDefault: '最初の慶州旅行ストーリーを投稿しましょう。', resetFilters: 'フィルターをリセット', placeLinked: '観光地リンク', attachmentPhoto: '{title}の添付写真', bookmarkRemove: 'ブックマーク解除', bookmarkSave: 'ブックマーク保存', edit: '編集', delete: '削除', loading: '読み込み中', loadingList: 'コミュニティを読み込み中',
      discardConfirm: '編集中の内容を破棄して閉じますか？', uploadPrepareFailed: 'アップロードを準備できませんでした。', browserConfigRequired: 'Supabaseのブラウザー設定が必要です。', imageRejected: '画像審査を通過しませんでした。', imageApproved: '画像の安全審査を通過しました。', imageUploadFailed: '画像をアップロードできませんでした。', storyFailed: 'ストーリーの下書きを作成できませんでした。', moderationMissing: '安全審査サービスが未設定のため投稿を保存できません。管理者にOpenAIの設定を依頼してください。', saveFailed: '投稿を保存できませんでした。', cancel: 'キャンセル', save: '保存', close: '閉じる', editPost: '投稿を編集', newPost: '新しい投稿', prompt: 'どんな話を共有しますか？', categoryLabel: '投稿カテゴリー', linkedPlace: 'リンクした観光地 · {id}', photo: '写真', fileHint: 'JPEG・PNG・WebP、10MB以下', previewAlt: '投稿写真のプレビュー', aiDraft: 'AI下書き', addPhoto: '旅行写真を追加してください', title: 'タイトル', titlePlaceholder: 'タイトルを入力', content: '内容', contentPlaceholder: '慶州旅行の思い出を聞かせてください', rating: '評価', points: '{value}点', privacyNote: '写真と文章は安全・個人情報審査後に公開されます。AI下書きは自動公開されません。', moderationUnavailable: '安全審査サービスが未設定のため作成・編集を完了できません。この環境にはOpenAIの設定が必要です。', saveChanges: '変更を保存', publish: '投稿する',
      postLoadFailed: '投稿を読み込めませんでした。', commentsLoadFailed: 'コメントを読み込めませんでした。', commentSaveFailed: 'コメントを保存できませんでした。', commentDeleteFailed: 'コメントを削除できませんでした。', reportConfirm: 'この投稿を運営に通報しますか？', reportSuccess: '通報を受け付けました。', reportFailed: '通報できませんでした。', blockConfirm: 'この投稿者をブロックして投稿を非表示にしますか？', blockFailed: '投稿者をブロックできませんでした。', postNotFound: '投稿が見つかりません。', backToList: '一覧へ', backToListLabel: 'コミュニティ一覧へ', postMenu: '投稿メニュー', report: '通報', blockAuthor: '投稿者をブロック', photoAlt: '{title}の写真{index}', edited: '編集済み', comments: 'コメント', commentInput: 'コメント入力', commentPlaceholder: '思いやりのあるコメントを残しましょう', commentPublish: 'コメントを投稿', commentDelete: 'コメント削除', firstComment: '最初のコメントを残しましょう。', changesSaved: '変更を保存しました。', detailLoading: '投稿を読み込み中', removePhoto: '写真を削除', localModerationNote: 'AI安全チェックがオフのため、個人情報と禁止語の基本チェックのみ適用されます。写真は形式と容量のみ確認します。'
    },
    course: {
      walking: '徒歩', car: '自動車', public: '公共交通', loadRecommendFailed: 'コースを提案できませんでした。', saveFailed: 'コースを保存できませんでした。', copied: '共有リンクをコピーしました。', header: 'AIおすすめコース', eyebrow: '実際の観光地データから', headline: '旅行条件に合うコースを作ります', purpose: '旅行目的', purposePlaceholder: '例：両親と新羅の歴史旅', duration: '期間', days: '{day}日', companion: '同行者', solo: 'ひとり', couple: 'カップル', family: '家族', friends: '友達', group: '団体', pace: '旅のペース', relaxed: 'ゆったり', balanced: 'バランス', packed: '充実', transport: '交通手段', interests: '興味', aiPlan: 'AIプラン', fallbackPlan: '基本プラン', shareLabel: 'コースを共有', saveLabel: 'コースを保存', durationSummary: '{distance}km・約{hours}時間', recommendedPlace: 'おすすめの場所', minutes: '{minutes}分', curatedTitle: '厳選おすすめコース', curatedDescription: 'テーマ別に用意した検証済みコースです。', courseSuffix: 'コース', deletedPlace: '削除された場所', savedNotice: 'コースを保存しました。下の「マイコース」で確認できます。', shareFailed: '共有できませんでした。', myCoursesTitle: 'マイコース', myCoursesDescription: '保存したAIコースと共有リンクです。'
    },
    itinerary: {
      loadFailed: '日程を読み込めませんでした。', createFailed: '日程を作成できませんでした。', saveOrderFailed: '日程の順序を保存できませんでした。', saveFailed: '日程を保存できませんでした。', invalidMetadata: '正しいタイトル・開始日・終了日を入力してください。', updateFailed: '日程を更新できませんでした。', deleteConfirm: '「{title}」を削除しますか？', deleteFailed: '日程を削除できませんでした。', defaultTitle: '私の慶州旅行', header: '私の日程', subtitle: '{start}～{end}・{count}か所', shareLabel: '日程を共有', emptyTitle: '日程がまだありません', emptyDescription: '新しい日程を作り、カートの場所を追加しましょう。', create: '日程を作成', newSchedule: '新しい日程', close: '閉じる', edit: '日程を編集', delete: '削除', title: '日程タイトル', startDate: '開始日', endDate: '終了日', saving: '保存中…', saveChanges: '変更を保存', timeline: 'タイムライン', calendar: 'カレンダー', timeUndecided: '時間未定', noPlaces: '場所がまだ追加されていません。', minutes: '{minutes}分', visitDate: '{name}の訪問日', visitTime: '{name}の訪問時間', moveUp: '{name}を上へ', moveDown: '{name}を下へ', drag: '{name}をドラッグして並べ替え', add: '追加', copied: '共有リンクをコピーしました。', shareFailed: '共有できませんでした。'
    },
    cart: {
      loadFailed: 'カートを読み込めませんでした。', saveFailed: '場所を保存できませんでした。', saved: '場所をカートに保存しました。', deleteFailed: '場所を削除できませんでした。', scheduleLoadFailed: '日程を読み込めませんでした。', defaultScheduleTitle: 'カート旅行', scheduleCreateFailed: '日程を作成できませんでした。', schedulePrepareFailed: '日程を準備できませんでした。', scheduleAddFailed: '日程に追加できませんでした。', addedToSchedule: '{count}か所を日程に追加しました。', header: '旅行カート', save: '保存', emptyTitle: '保存した場所がありません', emptyDescription: '上の一覧から場所を選んでカートに保存しましょう。', delete: '削除', selected: '選択', count: '{count}か所', traveler: '旅行者', addToSchedule: '日程に追加'
    },
    place: {
      loadFailed: '観光地を読み込めませんでした。', narrationFailed: 'AI解説を読み込めませんでした。', audioFailed: '音声を再生できませんでした。', cartSaved: 'カートに保存しました。', saveFailed: '保存できませんでした。', notFound: '観光地が見つかりません', backToMap: '地図へ戻る', information: '観光情報', hours: '営業時間', phone: '連絡先', narrationPrompt: '場所の物語を1分で聞いてみましょう', saveToCart: 'カートに保存', copied: 'リンクをコピーしました。', shareFailed: '共有できませんでした。'
    },
    auth: {
      kakaoNotConfigured: 'カカオログインのサーバー設定を確認してください。', kakaoCancelled: 'カカオログインがキャンセルされました。', kakaoAuthorizationFailed: 'カカオ認証を完了できませんでした。', kakaoCodeMissing: 'カカオ認証コードが届きませんでした。もう一度お試しください。', kakaoStateMismatch: 'ログイン要求が期限切れか無効です。もう一度お試しください。', kakaoTokenFailed: 'カカオ認証トークンを発行できませんでした。', kakaoUserFailed: 'カカオのユーザー情報を読み込めませんでした。', kakaoPersistenceFailed: '会員情報を保存できませんでした。しばらくしてからお試しください。', kakaoStateExpired: 'ログイン要求の期限が切れました。', kakaoLoginFailed: 'カカオログイン中にエラーが発生しました。', googleNotConfigured: 'Googleログインのサーバー設定を確認してください。', googleAuthorizationFailed: 'Googleログインを開始できませんでした。', callbackFailed: 'ログインリンクが期限切れか無効です。', demoFailed: 'デモログインに失敗しました。', networkError: 'ネットワーク接続を確認してください。', enterResetEmail: '上の欄に登録メールアドレスを入力してください。', resetMailFailed: '再設定メールを送信できませんでした。', resetMailSent: 'アカウントが存在する場合、パスワード再設定メールが送信されます。', nameTooShort: '名前は2文字以上で入力してください。', passwordMismatch: 'パスワードが一致しません。', genericError: 'エラーが発生しました。', verificationSent: '認証メールを送信しました。メールのリンクから登録を完了してください。', header: 'ログイン／新規登録', login: 'ログイン', signup: '新規登録', email: 'メールアドレス', name: '名前（2文字以上）', password: 'パスワード', passwordConfirm: 'パスワード確認', hidePassword: 'パスワードを隠す', showPassword: 'パスワードを表示', hidePasswordConfirm: '確認用パスワードを隠す', showPasswordConfirm: '確認用パスワードを表示', join: '登録する', forgotPassword: 'パスワードを忘れた方', kakaoLogin: 'カカオでログイン', googleLogin: 'Googleでログイン', demoLogin: 'デモアカウントを試す', continuePrefix: '続行すると', terms: '利用規約', privacy: 'プライバシーポリシー', continueSuffix: 'に同意したものとみなされます。', minEight: 'パスワードは8文字以上で入力してください。', authUnavailable: '認証サーバーが設定されていません。', updateFailed: 'パスワードを変更できませんでした。リンクの期限をご確認ください。', updated: 'パスワードを変更しました', returnService: 'サービスへ戻る', setNewPassword: '新しいパスワードを設定', passwordHint: '他のサービスで使っていない8文字以上のパスワードを使用してください。', newPassword: '新しいパスワード', change: '変更する'
    },
    settings: {
      loadFailed: 'アカウント情報を読み込めませんでした。', deleteFailed: 'アカウントを削除できませんでした。', networkError: 'ネットワーク接続を確認してください。', title: 'マイアカウント', traveler: '旅行者', loading: '読み込み中', terms: '利用規約', privacy: 'プライバシーポリシー', locationTerms: '位置情報サービス利用規約', deleteTitle: 'アカウントを完全に削除', deleteDescription: '日程、スタンプ、投稿、アップロードファイルが削除され、復元できません。続けるには下にDELETEと入力してください。', deleteConfirmLabel: 'アカウント削除の確認', deleteAction: 'アカウントとデータを削除'
    },
    stamp: { fallbackDescription: '慶州の現地スタンプ対象観光地です。', fallbackAddress: '慶州市', fieldCheck: '現地確認', hoursCheck: '営業時間を確認', tag: 'スタンプ', loadFailed: 'スタンプ図鑑を読み込めませんでした。', targetsMissing: 'スタンプ対象データが準備されていません。', retryNetwork: 'ネットワーク接続を確認してもう一度お試しください。', checkpointFirst: '現地案内板のQRチェックポイントを先に読み取ってください。', geoUnsupported: 'このブラウザーは位置情報に対応していません。', persistFailed: 'スタンプを保存できませんでした。もう一度お試しください。', duplicate: 'すでに獲得したスタンプです。', verified: '現地確認完了・距離{distance}m{delay}', rewardDelay: '・バッジ／特典を更新中', obtainFailed: 'スタンプを獲得できませんでした。', networkError: 'ネットワーク接続を確認してください。', permissionDenied: '位置情報が拒否されました。ブラウザー設定で許可してください。', locationFailed: '現在地を確認できませんでした。', consentSaveFailed: '位置情報の同意を保存できませんでした。', consentDetail: '{name}の現地範囲内にいるか一度だけ確認し、生の位置履歴は保存しません。', backAll: 'すべて見る', eyebrow: 'GPSと現地チェックポイントで確認', title: '慶州AIスタンプツアー', checkpointScanned: '現地QRチェックポイントを確認しました', checkpointLinked: 'リンクした場所の現地確認ボタンを押してください。', checkpointThis: 'この場所の現地確認ボタンを押してください。', loadErrorTitle: 'スタンプ図鑑に接続できません', retry: '再読み込み', progressPrompt: '承認済み観光地のスタンプを集めましょう', collected: '獲得スタンプ', badges: '獲得バッジ', rewards: 'デジタル特典', badgeWarning: 'バッジ情報の反映が遅れています。スタンプ記録には影響ありません。', catalogueTitle: '慶州スタンプ図鑑', catalogueDescription: '承認済みAIアートを優先し、ない場合は観光地写真を表示します。', loading: '読み込み中', emptyTitle: '開催中のスタンプ対象がありません', emptyDescription: '場所の同期とstamp target設定を確認してください。', stampAlt: '{name}のスタンプ', artDisplayFailed: 'AIアートの表示に失敗', photoFallback: '・写真で代替', modelTitle: '生成モデル：{model}', approvedArt: '承認済みAIアート', artGenerationFailed: 'AIアート生成に失敗', artGenerating: 'AIアートを生成中', artPending: 'AIアート承認待ち', attractionPhotoFailed: '観光地写真の表示に失敗', photoNoAi: '観光地写真・AI未生成', imagePreparing: '画像を準備中', qrReady: '現地QR確認済み', qrRequired: '現地QRが必要', recheck: 'もう一度確認', check: '現地確認', explore: 'ほかの旅行コースを見る', gpsWaiting: 'GPS信号を待っています…（最大15秒）', gpsSearching: 'GPS確認中・精度{accuracy}m（基準{max}m以内）', gpsTimeout: '十分に正確なGPS信号を取得できませんでした。空が開けた場所で再試行してください。', distanceHint: '現在地から{distance}m・許容範囲{radius}m', lastFix: '最新のGPS精度{accuracy}m' },
    shorts: { loadMore: 'ショートをもっと見る', loadFailed: 'ショート動画を読み込めませんでした。', audioFailed: '音声解説を再生できませんでした。', reactionFailed: 'リアクションを保存できませんでした。しばらくしてからお試しください。', shareFailed: '共有リンクを作成できませんでした。', title: '慶州ショート', introduction: '文化遺産の物語を、短い動画で楽しみましょう。', placeDetails: 'この場所の情報', filters: 'ショート動画のタグフィルター', loading: 'ショート動画を読み込み中', likeCount: 'いいね{count}件', reactionsUnavailable: 'サンプルのショート動画ではいいね・保存は利用できません。' },
    video: { videoLabel: '{title}の動画', youtubeTitle: '{title}のYouTube動画', buffering: '動画を読み込み中', failed: '動画を再生できないため、カバー画像を表示しています。', pause: '動画を一時停止', play: '動画を再生', unmute: '動画の音声をオン', mute: '動画をミュート' },
    share: { loadFailed: '共有内容を読み込めませんでした。', cannotOpen: '共有リンクを開けません', sharedCourse: '共有されたコース', sharedSchedule: '共有された日程', minutes: '{minutes}分', removedPlace: '削除された場所' },
    offline: { title: 'インターネット接続が必要です', description: '接続が復旧すると旅行情報と日程を再読み込みできます。', retry: '再接続' }
  },
  zh: {
    community: {
      all: '全部', review: '游记', tip: '攻略', food: '美食', lodging: '住宿', loadFailed: '无法加载社区。', bookmarkFailed: '无法更新收藏。', deleteConfirm: '要删除这篇帖子吗？', deleteFailed: '无法删除帖子。', deleted: '帖子已删除。', saved: '帖子已保存。', subtitle: '分享庆州旅行的瞬间与攻略', searchLabel: '搜索社区', searchPlaceholder: '搜索游记、地点和旅行攻略', filtersLabel: '社区筛选', savedFilter: '已收藏', loadErrorTitle: '无法加载社区', emptyTitle: '暂无旅行故事', emptySearch: '请尝试其他关键词或筛选条件。', emptyDefault: '分享第一篇庆州旅行故事吧。', resetFilters: '重置筛选', placeLinked: '关联景点', attachmentPhoto: '{title}的附件照片', bookmarkRemove: '取消收藏', bookmarkSave: '收藏', edit: '编辑', delete: '删除', loading: '加载中', loadingList: '正在加载社区',
      discardConfirm: '要放弃正在编辑的内容并关闭吗？', uploadPrepareFailed: '无法准备上传。', browserConfigRequired: '需要配置Supabase浏览器客户端。', imageRejected: '图片未通过审核。', imageApproved: '图片已通过安全审核。', imageUploadFailed: '无法上传图片。', storyFailed: '无法生成故事草稿。', moderationMissing: '安全审核服务尚未配置，无法保存帖子。请联系管理员配置OpenAI。', saveFailed: '无法保存帖子。', cancel: '取消', save: '保存', close: '关闭', editPost: '编辑帖子', newPost: '新帖子', prompt: '想分享什么故事？', categoryLabel: '帖子分类', linkedPlace: '关联景点 · {id}', photo: '照片', fileHint: 'JPEG、PNG或WebP，不超过10MB', previewAlt: '帖子照片预览', aiDraft: 'AI草稿', addPhoto: '添加旅行照片', title: '标题', titlePlaceholder: '请输入标题', content: '内容', contentPlaceholder: '分享你的庆州旅行故事', rating: '评分', points: '{value}分', privacyNote: '照片和文字通过安全与隐私审核后发布。AI草稿不会自动发布。', moderationUnavailable: '安全审核服务尚未配置，无法完成发布或编辑。此环境需要配置OpenAI。', saveChanges: '保存修改', publish: '发布',
      postLoadFailed: '无法加载帖子。', commentsLoadFailed: '无法加载评论。', commentSaveFailed: '无法保存评论。', commentDeleteFailed: '无法删除评论。', reportConfirm: '要向管理员举报这篇帖子吗？', reportSuccess: '举报已提交。', reportFailed: '无法提交举报。', blockConfirm: '要屏蔽该作者并隐藏帖子吗？', blockFailed: '无法屏蔽作者。', postNotFound: '未找到帖子。', backToList: '返回列表', backToListLabel: '返回社区', postMenu: '帖子菜单', report: '举报', blockAuthor: '屏蔽作者', photoAlt: '{title}照片{index}', edited: '已编辑', comments: '评论', commentInput: '输入评论', commentPlaceholder: '留下一条友善的评论吧', commentPublish: '发布评论', commentDelete: '删除评论', firstComment: '来发布第一条评论吧。', changesSaved: '修改已保存。', detailLoading: '正在加载帖子', removePhoto: '删除照片', localModerationNote: 'AI安全审核已关闭，仅进行个人信息和敏感词的基本检查。照片只检查格式和大小。'
    },
    course: {
      walking: '步行', car: '驾车', public: '公共交通', loadRecommendFailed: '无法推荐路线。', saveFailed: '无法保存路线。', copied: '分享链接已复制。', header: 'AI推荐路线', eyebrow: '基于真实景点数据', headline: '创建符合旅行条件的路线', purpose: '旅行目的', purposePlaceholder: '例如：和父母一起体验新罗历史', duration: '天数', days: '{day}天', companion: '同行人', solo: '独自', couple: '情侣', family: '家人', friends: '朋友', group: '团体', pace: '旅行节奏', relaxed: '悠闲', balanced: '适中', packed: '充实', transport: '交通方式', interests: '兴趣', aiPlan: 'AI方案', fallbackPlan: '基础方案', shareLabel: '分享路线', saveLabel: '保存路线', durationSummary: '{distance}公里 · 约{hours}小时', recommendedPlace: '推荐地点', minutes: '{minutes}分钟', curatedTitle: '精选推荐路线', curatedDescription: '按主题提前准备并验证的路线。', courseSuffix: '路线', deletedPlace: '已删除的地点', savedNotice: '路线已保存，可在下方“我的路线”中查看。', shareFailed: '无法分享。', myCoursesTitle: '我的路线', myCoursesDescription: '已保存的AI路线及其分享链接。'
    },
    itinerary: {
      loadFailed: '无法加载行程。', createFailed: '无法创建行程。', saveOrderFailed: '无法保存行程顺序。', saveFailed: '无法保存行程。', invalidMetadata: '请输入有效的标题、开始日期和结束日期。', updateFailed: '无法修改行程。', deleteConfirm: '要删除“{title}”行程吗？', deleteFailed: '无法删除行程。', defaultTitle: '我的庆州旅行', header: '我的行程', subtitle: '{start}～{end} · {count}个地点', shareLabel: '分享行程', emptyTitle: '暂无行程', emptyDescription: '创建新行程并从收藏夹添加地点吧。', create: '创建行程', newSchedule: '新行程', close: '关闭', edit: '编辑行程', delete: '删除', title: '行程标题', startDate: '开始日期', endDate: '结束日期', saving: '保存中…', saveChanges: '保存修改', timeline: '时间轴', calendar: '日历', timeUndecided: '时间未定', noPlaces: '尚未添加地点。', minutes: '{minutes}分钟', visitDate: '{name}的游览日期', visitTime: '{name}的游览时间', moveUp: '上移{name}', moveDown: '下移{name}', drag: '拖动{name}调整顺序', add: '添加', copied: '已复制分享链接。', shareFailed: '无法分享。'
    },
    cart: {
      loadFailed: '无法加载收藏夹。', saveFailed: '无法保存地点。', saved: '地点已保存到收藏夹。', deleteFailed: '无法删除地点。', scheduleLoadFailed: '无法加载行程。', defaultScheduleTitle: '收藏夹旅行', scheduleCreateFailed: '无法创建行程。', schedulePrepareFailed: '无法准备行程。', scheduleAddFailed: '无法添加到行程。', addedToSchedule: '已将{count}个地点添加到行程。', header: '旅行收藏夹', save: '保存', emptyTitle: '暂无收藏地点', emptyDescription: '从上方列表选择地点并保存到收藏夹吧。', delete: '删除', selected: '已选', count: '{count}个', traveler: '旅行者', addToSchedule: '添加到行程'
    },
    place: {
      loadFailed: '无法加载景点。', narrationFailed: '无法加载AI讲解。', audioFailed: '无法播放音频。', cartSaved: '已保存到收藏夹。', saveFailed: '无法保存。', notFound: '未找到景点', backToMap: '返回地图', information: '游览信息', hours: '开放时间', phone: '联系电话', narrationPrompt: '用一分钟聆听这个地点的故事', saveToCart: '保存到收藏夹', copied: '已复制链接。', shareFailed: '无法分享。'
    },
    auth: {
      kakaoNotConfigured: '请检查Kakao登录服务器配置。', kakaoCancelled: 'Kakao登录已取消。', kakaoAuthorizationFailed: '无法完成Kakao认证。', kakaoCodeMissing: '未收到Kakao授权码，请重试。', kakaoStateMismatch: '登录请求已过期或无效，请重试。', kakaoTokenFailed: '无法获取Kakao认证令牌，请重试。', kakaoUserFailed: '无法加载Kakao用户信息。', kakaoPersistenceFailed: '无法保存会员信息，请稍后重试。', kakaoStateExpired: '登录请求已过期，请重试。', kakaoLoginFailed: 'Kakao登录时发生错误。', googleNotConfigured: '请检查Google登录服务器配置。', googleAuthorizationFailed: '无法开始Google登录。', callbackFailed: '登录链接已过期或无效。', demoFailed: '演示账号登录失败。', networkError: '请检查网络连接。', enterResetEmail: '请先在上方输入注册邮箱。', resetMailFailed: '无法发送重置邮件。', resetMailSent: '如果账号存在，将发送密码重置邮件。', nameTooShort: '姓名至少输入2个字符。', passwordMismatch: '两次输入的密码不一致。', genericError: '发生错误。', verificationSent: '验证邮件已发送。点击邮件中的链接即可完成注册。', header: '登录／注册', login: '登录', signup: '注册', email: '邮箱地址', name: '姓名（至少2个字符）', password: '密码', passwordConfirm: '确认密码', hidePassword: '隐藏密码', showPassword: '显示密码', hidePasswordConfirm: '隐藏确认密码', showPasswordConfirm: '显示确认密码', join: '注册', forgotPassword: '忘记密码', kakaoLogin: '使用Kakao登录', googleLogin: '使用Google登录', demoLogin: '体验演示账号', continuePrefix: '继续即表示你同意', terms: '服务条款', privacy: '隐私政策', continueSuffix: '。', minEight: '密码至少输入8个字符。', authUnavailable: '认证服务器尚未配置。', updateFailed: '无法修改密码，请确认链接是否过期。', updated: '密码已修改', returnService: '返回应用', setNewPassword: '设置新密码', passwordHint: '请使用至少8个字符且未在其他服务中使用的密码。', newPassword: '新密码', change: '修改密码'
    },
    settings: {
      loadFailed: '无法加载账号信息。', deleteFailed: '无法删除账号。', networkError: '请检查网络连接。', title: '我的账号', traveler: '旅行者', loading: '加载中', terms: '服务条款', privacy: '隐私政策', locationTerms: '位置服务条款', deleteTitle: '永久删除账号', deleteDescription: '行程、印章、帖子和上传文件将被永久删除且无法恢复。请输入DELETE继续。', deleteConfirmLabel: '账号删除确认', deleteAction: '删除账号和数据'
    },
    stamp: { fallbackDescription: '庆州现场印章活动景点。', fallbackAddress: '庆州市', fieldCheck: '现场验证', hoursCheck: '确认开放时间', tag: '印章', loadFailed: '无法加载印章图鉴。', targetsMissing: '印章景点数据尚未准备好。', retryNetwork: '请检查网络连接后重试。', checkpointFirst: '请先扫描现场指示牌上的二维码。', geoUnsupported: '此浏览器不支持位置服务。', persistFailed: '印章未能保存，请重试。', duplicate: '你已经获得这个印章。', verified: '现场验证完成 · 距离{distance}米{delay}', rewardDelay: ' · 徽章/奖励更新中', obtainFailed: '无法获得印章。', networkError: '请检查网络连接。', permissionDenied: '位置权限已被拒绝，请在浏览器设置中允许。', locationFailed: '无法确认当前位置。', consentSaveFailed: '无法保存位置授权。', consentDetail: '仅验证一次你是否在{name}的现场范围内，不保存原始位置历史。', backAll: '查看全部', eyebrow: '通过GPS与现场检查点验证', title: '庆州AI印章之旅', checkpointScanned: '现场二维码已确认', checkpointLinked: '请点击关联地点的现场验证按钮。', checkpointThis: '请点击该地点的现场验证按钮。', loadErrorTitle: '无法连接印章图鉴', retry: '重新加载', progressPrompt: '收集已批准景点的印章', collected: '已收集印章', badges: '已获徽章', rewards: '数字奖励', badgeWarning: '徽章信息更新延迟，不影响印章记录。', catalogueTitle: '庆州印章图鉴', catalogueDescription: '优先显示已批准的AI作品；没有时使用景点照片。', loading: '加载中', emptyTitle: '暂无进行中的印章景点', emptyDescription: '请检查地点同步与stamp target设置。', stampAlt: '{name}印章', artDisplayFailed: 'AI作品显示失败', photoFallback: ' · 使用照片', modelTitle: '生成模型：{model}', approvedArt: '已批准AI作品', artGenerationFailed: 'AI作品生成失败', artGenerating: '正在生成AI作品', artPending: 'AI作品待审核', attractionPhotoFailed: '景点照片显示失败', photoNoAi: '景点照片 · 未生成AI作品', imagePreparing: '图片准备中', qrReady: '现场二维码已确认', qrRequired: '需要现场二维码', recheck: '再次验证', check: '现场验证', explore: '查看其他旅行路线', gpsWaiting: '正在等待GPS信号…（最多15秒）', gpsSearching: '正在确认GPS · 精度{accuracy}米（要求{max}米以内）', gpsTimeout: '未能获得足够精确的GPS信号，请在开阔处重试。', distanceHint: '距您{distance}米 · 允许半径{radius}米', lastFix: '最近GPS精度{accuracy}米' },
    shorts: { loadMore: '加载更多短片', loadFailed: '无法加载短视频。', audioFailed: '无法播放语音讲解。', reactionFailed: '无法保存互动，请稍后重试。', shareFailed: '无法创建分享链接。', title: '庆州短视频', introduction: '通过短视频，聆听文化遗产的故事。', placeDetails: '查看地点信息', filters: '短视频标签筛选', loading: '正在加载短视频', likeCount: '{count}次赞', reactionsUnavailable: '示例短视频不支持点赞和收藏。' },
    video: { videoLabel: '{title}视频', youtubeTitle: '{title} YouTube视频', buffering: '正在加载视频', failed: '视频无法播放，正在显示封面图片。', pause: '暂停视频', play: '播放视频', unmute: '打开视频声音', mute: '视频静音' },
    share: { loadFailed: '无法加载分享内容。', cannotOpen: '无法打开分享链接', sharedCourse: '分享的路线', sharedSchedule: '分享的日程', minutes: '{minutes}分钟', removedPlace: '已删除的地点' },
    offline: { title: '需要网络连接', description: '恢复连接后即可重新加载旅行信息和行程。', retry: '重新连接' }
  }
};
